#repos:
#  - repo: https://github.com/Yelp/detect-secrets
#    rev: v1.5.0
#    hooks:
#      - id: detect-secrets
#        args: ["--baseline", ".secrets.baseline"]
#        exclude: "node_modules|package-lock\\.json"

#repos:
#  - repo: https://github.com/zricethezav/gitleaks
#    rev: v8.18.0  # use the latest stable version
#    hooks:
#      - id: gitleaks
#        args: ["--redact"]  # optional, to mask secrets in output

repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        args:
          - "--config=.gitleaks.toml"
          - "--redact"
