name: Lint and Build

on: [push, pull_request]

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Composite Action
      uses: ./.github/actions/composite
      with:
        node-version: '18'
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo "This is a test job"
      shell: bash
    - name: Use Composite Action
      uses: ./.github/actions/composite
      with:
        node-version: '18'    

  
