name: Composite Action Workflow

on: [push, pull_request]

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Composite Action
        #uses: ./.github/actions/composite
        uses: poornesh.thatturi/actionshub@testactions
        with:
          node-version: '18'

  build-check:
    runs-on: ubuntu-latest
    needs: lint-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  type-check:
    runs-on: ubuntu-latest
    needs: lint-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
